format = """
[░▒▓](#a3aed2)\
$os\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nix_shell\
$rust\
[](fg:#212736 bg:#1d2230)\
$time\
[](fg:#1d2230)\
$fill\
[](fg:#1d2230)\
$cmd_duration\
[](fg:#212736 bg:#1d2230)\
[](fg:#394260 bg:#212736)\
[](fg:#769ff0 bg:#394260)\
$hostname\
[▓▒░](#a3aed2)\
\n$character"""

add_newline = false

[os]
disabled = false
style = 'bg:#a3aed2 fg:#090c0c'
[os.symbols]
NixOS = '  '

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "󰇘 "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nix_shell]
symbol = '󱄅'
style = "bg:#212736"
heuristic = true
format = '[[ $symbol ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[fill]
symbol = ' '

[cmd_duration]
min_time = 0
style = "bg:#1d2230"
format = '[[ $duration  ](fg:#a0a9cb bg:#1d2230)]($style)'

[hostname]
ssh_only = false
style = 'bg:#a3aed2 fg:#090c0c'
ssh_symbol = '  '
format = '[[$ssh_symbol](fg:#e3e5e5 bg:#769ff0)[](bg:#769ff0 fg:#a3aed2)$hostname ]($style)'

[character]
success_symbol = '[󱐋](bold green) '
error_symbol = '[✗](bold red) '
