palette = "night"
format = """
[░▒▓](text)\
$os\
[](fg:text bg:prim)\
$directory\
[](fg:prim bg:seco)\
$git_branch\
$git_status\
[](fg:seco bg:tert)\
$nix_shell\
$rust\
[](fg:tert bg:quar)\
$time\
[](fg:quar)\
$fill\

[](fg:quar)\
$cmd_duration\
[](fg:tert bg:quar)\
[](fg:seco bg:tert)\
[](fg:prim bg:seco)\
$hostname\
[▓▒░](text)\
\n[  ](seco)"""
right_format = """
$character"""

add_newline = false

[os]
disabled = false
style = 'bg:text fg:bg'
[os.symbols]
NixOS = '  '

[directory]
style = "fg:bg bg:prim"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "󰇘 "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[git_branch]
symbol = ""
style = "bg:seco"
format = '[[ $symbol $branch ](fg:bg bg:seco)]($style)'

[git_status]
style = "bg:seco"
format = '[[($all_status$ahead_behind )](fg:bg bg:seco)]($style)'

[nix_shell]
symbol = '󱄅'
style = "bg:tert"
heuristic = true
format = '[[ $symbol ](fg:bg bg:tert)]($style)'

[rust]
symbol = ""
style = "bg:tert"
format = '[[ $symbol ($version) ](fg:bg bg:tert)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:quar"
format = '[[  $time ](fg:seco bg:quar)]($style)'

[fill]
symbol = ' '

[cmd_duration]
min_time = 0
style = "bg:quar"
format = '[[ $duration  ](fg:seco bg:quar)]($style)'

[hostname]
ssh_only = false
style = 'fg:bg bg:text'
ssh_symbol = '  '
format = '[[$ssh_symbol](fg:bg bg:prim)[](bg:prim fg:text)$hostname ]($style)'

[character]
success_symbol = '[󱐋](bold green) '
error_symbol = '[✗](bold red) '

[palettes.night]
prim = "#a2b3e6"
seco = "#738cd9"
tert = "#4566cd"
quar = "#0f2d8a"
red = "#f38ba8"
green = "#a6e3a1"
text = "#d0d9f2"
bg = "#1E1E2E"
